apiVersion: apps/v1
kind: Deployment
metadata: # metadata about the Deployment
  name: rms-deployment
spec: # defines the desired state of the Deployment.
  replicas: 2 # specifies how many identical replicas (pods) of the application should
              # be maintained, in this case, 2, which means Kubernetes will ensure that two pods running
              # the specified container are always available
  selector:
    matchLabels:
      app: rms-docker-img
  template: # defines the pod template used by the Deployment. It specifies the pod's
             # metadata and the container(s) to run.
    metadata: # specifies the pod's metadata
      labels:
        app: rms-docker-img
    spec: # specifies the container(s) to run
      containers:
      - name: rms-container
        image: chunkangso/rms-docker-img:v4
        ports:
        - containerPort: 5050 # specifies the port that the application listens on
